# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180815_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='static/image/banner/%Y/%m', verbose_name='轮播图'),
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(upload_to='static/image/photo/%Y/%m'),
        ),
    ]
