# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180816_1432'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
