# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 15:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=30, verbose_name='获得时间')),
                ('name', models.CharField(default='', max_length=100, verbose_name='奖项名称')),
                ('members', models.CharField(default='', max_length=200, verbose_name='奖项名称')),
                ('place', models.CharField(default='', max_length=200, verbose_name='授予单位')),
            ],
            options={
                'verbose_name': '奖项荣誉',
                'verbose_name_plural': '奖项荣誉',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='标题')),
                ('content', models.CharField(default='', max_length=300, verbose_name='内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '最新消息',
                'verbose_name_plural': '最新消息',
            },
        ),
    ]
