# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Introduce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(default='', max_length=500, verbose_name='介绍')),
                ('dream', models.CharField(default='', max_length=500, verbose_name='愿景')),
                ('team', models.CharField(default='', max_length=500, verbose_name='团队')),
                ('image', models.ImageField(upload_to='image/%Y/%m')),
            ],
            options={
                'verbose_name': '工作室概况',
                'verbose_name_plural': '工作室概况',
            },
        ),
    ]
