# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_introduce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduce',
            name='image',
            field=models.ImageField(upload_to='static/image/%Y/%m'),
        ),
    ]
