# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_jiangx'),
    ]

    operations = [
        migrations.AddField(
            model_name='honor',
            name='category',
            field=models.CharField(choices=[('compet', '竞赛'), ('proj', '项目'), ('invent', '发明'), ('paper', '论文')], default='compet', max_length=20, verbose_name='种类'),
        ),
    ]
