# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0006_honor_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='honor',
            options={'verbose_name': '团队荣誉', 'verbose_name_plural': '团队荣誉'},
        ),
        migrations.AddField(
            model_name='honor',
            name='grade',
            field=models.CharField(default='', max_length=200, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='honor',
            name='members',
            field=models.CharField(choices=[('national', '国家级'), ('provincial', '省级'), ('school', '校级')], default='national', max_length=200, verbose_name='奖项名称'),
        ),
    ]
