# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0008_auto_20180816_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honor',
            name='grade',
            field=models.CharField(choices=[('国家级', '国家级'), ('省级', '省级'), ('校级', '校级')], default='国家级', max_length=200, verbose_name='级别'),
        ),
    ]
