# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0009_auto_20180816_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(default='', max_length=1000, verbose_name='内容'),
        ),
    ]
